# to use this:
# docker buildx build -o out/ .
# (will copy the rootfs of `output` to out/)

FROM ubuntu:22.04 as build

RUN apt update -y
RUN apt upgrade -y
# RUN apt install build-essential libgdbm-dev python3.7-gdbm

WORKDIR /root/
COPY src/ src/
COPY Makefile .
# ...
# alternatively:
# COPY . .
# (caution: will copy artifacts in out/ back into the container next run)

# make blah
# ...

FROM scratch as output
COPY --from=build /root/Makefile .
COPY --from=build /root/src/ .
