#!/bin/bash

options="--"

PFX=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/")

export PIN_ROOT=$PFX/pin-tool

# make sure to compile the tooling.
make -C $PFX --no-print-directory pin-tool
make -C $PFX --no-print-directory obj-intel64/profile.so
# make sure e9patch exists.
pushd $PFX >/dev/null
  if [ ! -d e9patch ]; then
    git clone https://github.com/GJDuck/e9patch.git
    cd e9patch && ./build.sh
  fi
  export PATH=$PFX/e9patch:$PATH
popd >/dev/null

# Disabling ASLR with setarch
pin="setarch x86_64 -R $PFX/pin-tool/pin"

if [ "$1" = "" ]; then
    $pin -ifeellucky -t $$PFX/obj-intel64/reinterp.so -help -- /bin/ls
    exit 1
fi

if [[ "$1" =~ ^- ]]; then
    options=""
fi

modules="-ifeellucky -t $PFX/obj-intel64/profile.so"
$pin $modules $options $* || true
