#!/bin/bash

options="--"

PFX=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/")




export PIN_ROOT=$PFX/pin-tool

# if PIN_ROOT is not found
if [ ! -d $PIN_ROOT ]; then
    pushd $PFX
        wget https://software.intel.com/sites/landingpage/pintool/downloads/pin-external-3.31-98869-gfa6f126a8-gcc-linux.tar.gz
        tar xf pin-external*.tar.gz
        rm pin-external*.tar.gz
        mv pin-external*/ $PIN_ROOT
    popd
fi

# make sure to compile the tooling.
make -C $PFX --no-print-directory pin-tool
make -C $PFX --no-print-directory intel64

# Disabling ASLR with setarch
pin="setarch x86_64 -R $PFX/pin-tool/pin"

if [ "$1" = "" ]; then
    $pin -ifeellucky -t $$PFX/obj-intel64/reinterp.so -help -- /bin/ls
    exit 1
fi

if [[ "$1" =~ ^- ]]; then
    options=""
fi

modules="-ifeellucky -t $PFX/obj-intel64/profile.so"
$pin $modules $options $* || true
